# Generated by Django 4.2.7 on 2024-05-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=30)),
            ],
        ),
    ]
