# Generated by Django 4.2.7 on 2024-05-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_category_remove_lesson_category_userprofile_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lessons_completed',
            field=models.ManyToManyField(blank=True, to='sign.lesson'),
        ),
    ]
