# Generated by Django 4.2.7 on 2024-05-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_alter_userprofile_lessons_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lessons_completed',
            field=models.ManyToManyField(null=True, to='sign.lesson'),
        ),
    ]
