# Generated by Django 4.2.7 on 2024-06-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tests_completed',
            field=models.ManyToManyField(null=True, related_name='completed_tests', to='sign.lesson'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lessons_completed',
            field=models.ManyToManyField(null=True, related_name='completed_lessons', to='sign.lesson'),
        ),
    ]
