# Generated by Django 4.2.13 on 2024-06-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0007_remove_userprofile_lessons_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture_file',
            field=models.FileField(null=True, upload_to='category_pictures/'),
        ),
    ]
